### ISSUE TITLE
Add PassCode to Rules Entry

### ISSUE THREAD

**Issue by CMTeam2017** [CMTeam2017/CheckMate-UI---26Sep17#10]
### Expected Behaviour
Assigned PassCode is equivalent to the rule set by the CallerID, CNAME, or Alias.  The PassCode may by used as a unique identifier or used for many numbers as a group of callers, ie: family members calling from different locations

**Comment by lisacopeland** [comment]
More information? the passcode field is provided for these routing options - how is this a bug?

**Comment by CMTeam2017** [comment]
My error, sorry.  Some additional components are needed.  I'll work on that.
