### ISSUE TITLE
Wildcard rule is ignored by non-VIP number 

### ISSUE THREAD

**Issue by CMTeam2017** [CMTeam2017/CheckMate-UI---26Sep17#14]
### Expected Behaviour
Routing rule should be in force
### Actual Behaviour
Ignored
### Steps To Reproduce Behaviour
415* rule active, added 4157635540, routing option used was 4157635540, not the wildcard rule.  Added VIP just to test true/false programming, nothing changed (true or false)

**Comment by lisacopeland** [comment]
Did you test this before Kenneth added the functionality to regard VIPs?
