### ISSUE TITLE
Hangup option playing OGM instead on Phone Line Rule

### ISSUE THREAD

**Issue by CMTeam2017** [CMTeam2017/CheckMate-UI---26Sep17#17]

**Comment by lisacopeland** [comment]
I need more info - can you please give me a  reproduction scenario?

**Comment by CMTeam2017** [comment]
Setting the Hangup option on Inbound calls does not hangup.  It plays an OGM.

**Comment by lisacopeland** [comment]
This is because the dropdown contains the first option as a default and will not allow the field to be empyt

**Comment by lisacopeland** [comment]
This is now fixed - the user can now leave the drop down blank
