### ISSUE TITLE
ruleTarget not being sent with request to addRule

### ISSUE THREAD

**Issue by kharmon11** [CMTeam2017/CheckMate-UI---26Sep17#21]
### Expected Behaviour
When adding a rule in the UI, a ruleTarget field is part of the request to the addRule API.

### Actual Behaviour
ruleTarget is not in the request.

### Steps To Reproduce Behaviour
Create a phone rule in the UI.

The addRule API had would return a "missingInput" successCode. The API has been modified to allow a request to not have ruleTarget. However, that requirement will need to be out back in, eventually.

**Comment by lisacopeland** [comment]
I have added this field - I am placing '0' whenever I save a phone rule
