### ISSUE TITLE
Hang-up routing  option includes an OGM when it should not.

### ISSUE THREAD

**Issue by kharmon11** [CMTeam2017/CheckMate-UI---26Sep17#22]
### Expected Behaviour
When a Hang-up routing option is selected, it should not include an ogmId.

### Actual Behaviour
An ogmId is included with a Hang-up routing option when creating rules in the UI.

### Steps To Reproduce Behaviour
On a custom Phone Rules screen, create a rule with a Hang-up routing option. There will be a an OGM field, which should not be there. Also, the OGM can not be removed. Create the rule, and all calls that rule applies to will use an OGM.

**Comment by lisacopeland** [comment]
The OGM Field is optional for this routing option - it should not fill in a default so the user does not have to have it

**Comment by lisacopeland** [comment]
This is now fixed
