### ISSUE TITLE
reoccurring scheduled DND rules generates inaccurate start and end times. 

### ISSUE THREAD

**Issue by kharmon11** [CMTeam2017/CheckMate-UI---26Sep17#23]
### Expected Behaviour
On the DND page: when I create a scheduled non-reoccurring DND, the correct start and end times should be displayed on the screen and the correct start and end times should be stored in the database.

### Actual Behaviour
When a non-reoccurring DND is created, incorrect start and end times are displayed and stored in the database.

### Steps To Reproduce Behavior
Open up the DND page on in the UI. Make ReOccurring false and select Scheduled. Enter start and end times. Click the save button.

**Comment by lisacopeland** [comment]
Could you please give me a more specific repro scenario? It seems like it works - do you recall that the times are handled differently between reoccurring and not? time values for reoccurring should be strings like '09:00' and '21:00' whereas they are timestamps for non-reoccurring

**Comment by lisacopeland** [comment]
As we discussed, this has to do with UTC times - I am still investigating

**Comment by lisacopeland** [comment]
I have fixed this
