### ISSUE TITLE
ogmId field and value remains in rule when changed from OGM to Hang-up

### ISSUE THREAD

**Issue by kharmon11** [CMTeam2017/CheckMate-UI---26Sep17#4]
When a phoneRule is created or updated to an OGM routingOption type, and then the same rule is updated to a Hang-up type, the ogmId field and value remain the rule's routingOption sub-document. This causes call responses like this:
0:1:5a2eb215a9231857eb963089::
...to be created, when it should be 0:1:::

Currently, the first response type is still treated as a Hang-up by the device, but this could errors in the future. 

Either the rule update should remove the ogmId value, or the inboundcall API should ignore an ogmId value when constructing a response string for a rule with a hangupType of 1.

**Comment by lisacopeland** [comment]
I have made the field values reset every time the routing option is changed. Let me know if there are any issues with this.
