### ISSUE TITLE
Can't save a scheduled DND from 11PM-6AM

### ISSUE THREAD

**Issue by CMTeam2017** [CMTeam2017/CheckMate-UI---26Sep17#7]
### Actual Behaviour
Save button greyed

**Comment by lisacopeland** [comment]
Ah - Yes, the algorithm for deciding if a block is valid doesn't take into account when a block goes to the next day

**Comment by lisacopeland** [comment]
The UI now allows for an end time that is earlier than the start time for a scheduled non-reoccurring block. The end time is now saved as a time the following day.
