### ISSUE TITLE
Expired DNDs should get expunged

### ISSUE THREAD

**Issue by lisacopeland** [CMTeam2017/CheckMate-UI---26Sep17#9]
### Expected Behaviour
When Dnd's are listed only the active ones should display and blocks should disappear when 
they are expired
### Actual Behaviour
Dnds that are in the past show up in the list and still exist in the database
### Steps To Reproduce Behaviour
Create a Dnd for x minutes - let  the time go past, bring up the Dnds for that entity - you will see that
they are still in the list

**Comment by lisacopeland** [comment]
this is partially fixed - the user will not see an expired block. Even if the expired blocks exist in the database they should not affect the checkmate

**Comment by kharmon11** [comment]
I will need to look into it more, but I think I could make a non-reoccurring DND record automatically get deleted at its endTime value.

**Comment by lisacopeland** [comment]
ok - that would be great


---------------------------------------------
For more information about boarding and training, please visit my website, www.sansebastianec.com<http://www.sansebastianec.com>


________________________________

**Comment by lisacopeland** [comment]
Does that mean I won't need to check for expired Dnd records when I call the get?

---------------------------------------------
For more information about boarding and training, please visit my website, www.sansebastianec.com<http://www.sansebastianec.com>


________________________________

**Comment by kharmon11** [comment]
Yes, as the record will be deleted. It could be deleted up to a minute late, but that probably would not matter.

**Comment by lisacopeland** [comment]
no worries - I'll just not display it if it is expired


Doin anything tonight?


---------------------------------------------
For more information about boarding and training, please visit my website, www.sansebastianec.com<http://www.sansebastianec.com>


________________________________

**Comment by lisacopeland** [comment]
The UI now checks whether a DND is expired and doesn't display it, this will prevent expired records that haven't been expunged to display - I'll close this when Kenneth tells me that he is having these records deleted when they expire

**Comment by kharmon11** [comment]
I forgot to mention: I got expired DND records to delete themselves successfully.
